version: "3.2"
services:

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
    
    app:
        links:
            - redis
        build: ./
        ports: 
            - "8080:8080"
        volumes: 
            - ./storage:/storage
            - /tmp:/tmp

volumes:
    redisdata:
        driver: "local"
