version: "3.2"
services:

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
    
    app:
        links:
            - redis
        build: ./
        ports: 
            - "8080:${APP_PORT}"
        volumes: 
            - ./storage:/storage
            - /tmp:/tmp
        environment: 
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            APP_PORT: ${APP_PORT}
            STORAGE_PATH: ${STORAGE_PATH}

volumes:
    redisdata:
        driver: "local"
